### ISSUE TITLE
Error with webpack cli

### ISSUE THREAD

**Issue by jarkin13** [webpack-contrib/compression-webpack-plugin#125]
- Operating System: macOS Mojave
- Node Version: v11.10.0
- NPM Version: 6.7.0
- webpack Version: 4.30.0
- webpack cli version: 3.3.3"
- compression-webpack-plugin Version: 3

### Expected Behavior
When adding `const CompressionPlugin = require('compression-webpack-plugin');` --> this should not break my build

When adding
```
const CompressionPlugin = require('compression-webpack-plugin');

module.exports = {
  plugins: [new CompressionPlugin()],
};
```

this should also not break my build

### Actual Behavior
Both break my build.

### Code

```js
// webpack.config.js
// ---------
```
[File link](https://gist.github.com/jarkin13/2ad87c57d83f898ee9892212670ef37c)

```js
// assets.js
// ---------
```
[File link](https://gist.github.com/jarkin13/5abee13b443a037e83ba2593f923306f)

### Error Message
```
/Users/username/Workspace/example/wp-content/themes/paxton/node_modules/webpack-cli/bin/cli.js:74
				throw err;
				^

Error: Cannot find module 'webpack/lib/ModuleFilenameHelpers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (/Users/username/Workspace/example/wp-content/themes/paxton/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/username/Workspace/example/node_modules/compression-webpack-plugin/dist/index.js:18:53)
    at Module._compile (/Users/username/Workspace/example/wp-content/themes/paxton/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (/Users/username/Workspace/example/wp-content/themes/paxton/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/username/Workspace/example/node_modules/compression-webpack-plugin/dist/cjs.js:3:18)
    at Module._compile (/Users/username/Workspace/example/wp-content/themes/paxton/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (/Users/username/Workspace/example/wp-content/themes/paxton/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/username/Workspace/example/wp-content/themes/paxton/webpack/tasks/assets.js:82:27)
    at Module._compile (/Users/username/Workspace/example/wp-content/themes/paxton/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (/Users/username/Workspace/example/wp-content/themes/paxton/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/username/Workspace/example/wp-content/themes/paxton/webpack.config.js:6:16)
    at Module._compile (/Users/username/Workspace/example/wp-content/themes/paxton/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (/Users/username/Workspace/example/wp-content/themes/paxton/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
```

**Comment by evilebottnawi** [comment]
Something wrong with setup, looks you have very old version of webpack. Can you create reproducible test repo?

**Comment by jarkin13** [comment]
@evilebottnawi I just upgraded my webpack to 4.33.0 — I don't believe it was that outdated(from 4.3) and I'm still running into the same problem.

**Comment by evilebottnawi** [comment]
@jarkin13 maybe you have globally installed webpack, can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!
