### ISSUE TITLE
Error: Cannot find module 'webpack/lib/RawSource'

### ISSUE THREAD

**Issue by gajus** [webpack-contrib/compression-webpack-plugin#19]
``` sh
module.js:341
    throw err;
    ^

Error: Cannot find module 'webpack/lib/RawSource'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/var/www/showtime-app/node_modules/compression-webpack-plugin/index.js:7:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/home/web/.nvm/versions/node/v5.6.0/bin/node" "/home/web/.nvm/versions/node/v5.6.0/bin/npm" "run" "build"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! showtimes@ build: `NODE_ENV=production webpack --config ./webpack.config.production.js --progress`
npm ERR! Exit status 1
```

This seems to be caused by `compression-webpack-plugin`.

**Comment by gajus** [comment]
@sokra Are you waiting for a PR?

**Comment by erwingaitano** [comment]
Are you using Webpack 2? I'm having the same problem with that version of webpack. In webpack 1.x just works fine.

**Comment by gajus** [comment]
Using webpack 2.

**Comment by michael-ciniawsky** [comment]
@gajus @erwingaitano @zhaoyangsoft Still not working with lastest webpack and compression-webpack-plugin?

**Comment by michael-ciniawsky** [comment]
Reopen if still any regressions or open a new issue :)
