### ISSUE TITLE
TypeError: Cannot read property 'tapPromise' of undefined for webpack 5.5.1

### ISSUE THREAD

**Issue by lijianq** [webpack-contrib/compression-webpack-plugin#222]
when I tried "compression-webpack-plugin": "^6.1.1" with webpack 5.5.1 and run yarn build it reports:

yarn build
yarn run v1.22.10
$ vue-cli-service build

⠙  Building for production...Starting type checking service...
Using 1 worker with 2048MB memory limit
✔  Building for production...
 ERROR  TypeError: Cannot read property 'tapPromise' of undefined
TypeError: Cannot read property 'tapPromise' of undefined
    at /Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/compression-webpack-plugin/dist/index.js:349:41
    at SyncHook.eval [as call] (eval at create (/Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:630:30)
    at /Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:529:11)
    at /Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:318:10
    at eval (eval at create (/Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at run (/Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:248:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/lijianq/work/workspaces/prototype/adminconsole/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:315:19
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The full package.json as follow:

{
  "name": "adminconsole",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@ant-design-vue/pro-layout": "^1.0.5",
    "umi-request": "^1.3.5",
    "ant-design-vue": "^1.7.1",
    "core-js": "^3.6.5",
    "moment": "^2.29.1",
    "register-service-worker": "^1.7.1",
    "store": "^2.0.12",
    "vue": "^2.6.11",
    "vue-container-query": "^0.1.0",
    "vue-class-component": "^7.2.3",
    "vue-i18n": "^8.22.1",
    "vue-property-decorator": "^8.4.2",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0",
    "vuex-module-decorators": "^1.0.1",
    "vuex-persist": "^3.1.3",
    "md5": "^2.3.0",
    "viser-vue": "^2.4.8",
    "vue-cropper": "^0.5.5",
    "axios": "^0.21.0"
  },
  "devDependencies": {
    "@ant-design/colors": "^3.2.1",
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-pwa": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-typescript": "^5.0.2",
    "@babel/core": "^7.12.3",
    "babel-plugin-import": "^1.13.1",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "less": "^3.12.2",
    "less-loader": "^7.0.2",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "babel-loader": "^8.2.1",
    "typescript": "~3.9.3",
    "vue-template-compiler": "^2.6.11",
    "webpack": "^5.5.1",
    "webpack-theme-color-replacer": "^1.3.14",
    "compression-webpack-plugin": "^6.1.1"
  }
}

config:

if (isProd) {
    vueConfig.configureWebpack.plugins.push(new CompressionWebpackPlugin({
        filename: '[path].gz[query]',
        algorithm: 'gzip',
        test: new RegExp('\\.(' + productionGzipExtensions.join('|') + ')$'),
        threshold: 10240,
        minRatio: 0.8
    }))
}

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
