### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'tapPromise')

### ISSUE THREAD

**Issue by hesiyuetian** [webpack-contrib/compression-webpack-plugin#315]
CODE:

new CompressionWebpackPlugin({
    filename: "[path][base].gz",
    algorithm: "gzip",
    test: /\.js$|\.css$|\.html$/,
    threshold: 10240,
    minRatio: 0.8,
  }),

ERROR: 

TypeError: Cannot read properties of undefined (reading 'tapPromise')
    at /Users/lydia/Desktop/react/halo-manage-react/node_modules/compression-webpack-plugin/dist/index.js:414:39
    at SyncHook.eval [as call] (eval at create (/Users/lydia/Desktop/react/halo-manage-react/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/lydia/Desktop/react/halo-manage-react/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/lydia/Desktop/react/halo-manage-react/node_modules/webpack/lib/Compiler.js:630:30)
    at /Users/lydia/Desktop/react/halo-manage-react/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lydia/Desktop/react/halo-manage-react/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lydia/Desktop/react/halo-manage-react/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/lydia/Desktop/react/halo-manage-react/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/lydia/Desktop/react/halo-manage-react/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/Users/lydia/Desktop/react/halo-manage-react/node_modules/webpack/lib/Compiler.js:529:11)
    at /Users/lydia/Desktop/react/halo-manage-react/node_modules/webpack/lib/Compiler.js:318:10
    at _next1 (eval at create (/Users/lydia/Desktop/react/halo-manage-react/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at eval (eval at create (/Users/lydia/Desktop/react/halo-manage-react/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by alexander-akait** [comment]
Sorry, you have an old version of `webpack`, the latest version of the plugin requires the latest version of `webpack` (v5)
