### ISSUE TITLE
Error running install script for optional dependency

### ISSUE THREAD

**Issue by Igor-Vuk** [webpack-contrib/compression-webpack-plugin#66]
When I install this plugin I keep getting this error in console. It happens when I wanna install or remove any npm package.

```
Error running install script for optional dependency: "C:\\Users\\igvuk\\Desktop\\Projects-git\\Ultimate React Boilerplate\\node_modules\\node-zopfli: Command failed.\nExit code: 1\nCommand: C:\\WINDOWS\\system32\\cmd.exe\nArguments: /d /s /c node-pre-gyp install --fallback-to-build\nDirectory: C:\\Users\\igvuk\\Desktop\\Projects-git\\Ultimate React Boilerplate\\node_modules\\node-zopfli
\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.36\nnode-pre-gyp info using node@8.1.3 | win32 | x64\nnode-pre-gyp info check checked for \"C:\\Users\\igvuk\\Desktop\\Projects-git\\Ultimate React Boilerplate\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64\\zopfli.node\" (not found)\nnode-pre-gyp http GET https://node-zopfli.s3.amaz
onaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz\nnode-pre-gyp http 403 https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz\nnode-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@8.1.3 (node-v57 ABI) (fa
lling back to source compile with node-gyp) \nnode-pre-gyp http 403 status code downloading tarball https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@8.1.3 | win32 | x64\ngyp info ok \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using n
ode@8.1.3 | win32 | x64\ngyp ERR! configure error \ngyp ERR! stack Error: Can't find Python executable \"python\", you can set the PYTHON env variable.\ngyp ERR! stack     at PythonFinder.failNoPython (C:\\Users\\igvuk\\Desktop\\Projects-git\\Ultimate React Boilerplate\\node_modules\\node-gyp\\lib\\configure.js:483:19)\ngyp ERR! stack     at PythonFinder.<anonymous> (C:\\Users\\igvuk\\Desktop\\P
rojects-git\\Ultimate React Boilerplate\\node_modules\\node-gyp\\lib\\configure.js:508:16)\ngyp ERR! stack     at C:\\Users\\igvuk\\Desktop\\Projects-git\\Ultimate React Boilerplate\\node_modules\\graceful-fs\\polyfills.js:284:29\ngyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)\ngyp ERR! System Windows_NT 10.0.14393\ngyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\
\\Users\\\\igvuk\\\\Desktop\\\\Projects-git\\\\Ultimate React Boilerplate\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=C:\\\\Users\\\\igvuk\\\\Desktop\\\\Projects-git\\\\Ultimate React Boilerplate\\\\node_modules\\\\node-zopfli\\\\lib\\\\binding\\\\node-v57-win32-x64\\\\zopfli.node\" \"--module_name=zopfli\" \"--module_path=C:\\\\Users\\\\i
gvuk\\\\Desktop\\\\Projects-git\\\\Ultimate React Boilerplate\\\\node_modules\\\\node-zopfli\\\\lib\\\\binding\\\\node-v57-win32-x64\"\ngyp ERR! cwd C:\\Users\\igvuk\\Desktop\\Projects-git\\Ultimate React Boilerplate\\node_modules\\node-zopfli\ngyp ERR! node -v v8.1.3\ngyp ERR! node-gyp -v v3.6.2\ngyp ERR! not ok \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute
'C:\\Program Files\\nodejs\\node.exe C:\\Users\\igvuk\\Desktop\\Projects-git\\Ultimate React Boilerplate\\node_modules\\node-gyp\\bin\\node-gyp.js configure --fallback-to-build --module=C:\\Users\\igvuk\\Desktop\\Projects-git\\Ultimate React Boilerplate\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64\\zopfli.node --module_name=zopfli --module_path=C:\\Users\\igvuk\\Desktop\\Projects
-git\\Ultimate React Boilerplate\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64' (1)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\\Users\\igvuk\\Desktop\\Projects-git\\Ultimate React Boilerplate\\node_modules\\node-pre-gyp\\lib\\util\\compile.js:83:29)\nnode-pre-gyp ERR! stack     at emitTwo (events.js:125:13)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (event
s.js:213:7)\nnode-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)\nnode-pre-gyp ERR! System Windows_NT 10.0.14393\nnode-pre-gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\igvuk\\\\Desktop\\\\Projects-git\\\\Ultimate React Boilerplate\\\\n
```

**Comment by d3viant0ne** [comment]
https://github.com/webpack-contrib/compression-webpack-plugin/releases/tag/v1.0.0-beta.1

**Comment by Igor-Vuk** [comment]
@d3viant0ne Thanks. Everything is ok now.
